[build-system]
requires = [
    "setuptools>=77.0",
    "wheel"
]
build-backend = "setuptools.build_meta"


[project]
name = "afrimarkets"
version = "0.1.0"
description = "African financial markets data access and analysis"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "requests>=2.31",
    "beautifulsoup4>=4.12",
    "pandas>=2.2"
]